# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # setup_mongo_action:
  #   runs-on: ubuntu-latest
  #   name: mongo
  #   steps:
  #     - name: Create mongo Docker container
  #       id: build_mongo_docker
  #       uses: DigiPie/mongo-action@v1.0.1
  #       with:
  #         image-version: latest
  #         port: 27017

  # setup_redis_action:
  #   runs-on: ubuntu-latest
  #   name: redis
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: shogo82148/actions-setup-redis@v1
  #       with:
  #         redis-version: '6.x'

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # needs: [setup_redis_action, setup_mongo_action]
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.1
        with:
          image-version: latest
          port: 27017

      - run: redis-cli ping
      - run: yarn
      - run: yarn build
      - run: yarn lint
